server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/a3m_user_db
    username: a3m_app
    password: a3madmin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret: ta_cle_secrete_jwt  # À remplacer par une clé sécurisée (ex: 256 bits)
  expiration: 86400  # 24h en secondes
